public/index.html
+ Fixed Zephir version
+ Fixed line ends (converted to the `LF`)
=> Fixed Zephir version

public/css/style.css
=> Fixed buttons size

storage/languages/en.json
Zephir doesn't appear in the search results unless you search for Zephir
=> Change title to improve positioning

_config.yml
=> update to current version

_includes/meta.html, assets/favicons/site.webmanifest
=> add webmanifest & upd meta

_includes/js.html
=> fix console errors

language/en.html
https://github.com/zephir-lang/zephir-website/issues/100
=> change logo to svg

_data/uk-UA.json
https://github.com/zephir-lang/zephir-website/issues/102
=> fix transition

_sass/_general.scss
https://github.com/zephir-lang/zephir-website/issues/207
=> update content styles

language/zh-CN.html
https://github.com/zephir-lang/zephir-website/issues/209
=> update zh lang links

language/uk-UA.html
https://github.com/zephir-lang/zephir-website/issues/211
=> update uk lang links

language/tr-TR.html
https://github.com/zephir-lang/zephir-website/issues/213
=> update tr lang links

language/ru-RU.html
https://github.com/zephir-lang/zephir-website/issues/215
=> update ru lang links

language/el-GR.html
https://github.com/zephir-lang/zephir-website/issues/219
=> update el lang links

css/style.scss
resolve https://github.com/zephir-lang/zephir-website/issues/240
=> fix netlify build

_includes/meta.html
resolve https://github.com/zephir-lang/zephir-website/issues/264
=> reformat meta.html

_includes/meta-404.html
resolve https://github.com/zephir-lang/zephir-website
=> reformat meta404.html

404.html
resolve https://github.com/zephir-lang/zephir-website/issues/268
=> reformat 404.html

_data/en.json, language/en.html
resolve https://github.com/zephir-lang/zephir-website/issues/272
=> remove Discussions link en

_data/en-US.json
resolve https://github.com/zephir-lang/zephir-website/issues/276
=> remove Discussions link en-us

_data/es-ES.json, language/es-ES.html
resolve https://github.com/zephir-lang/zephir-website/issues/278
=> remove Discussions link es

_data/ru-RU.json, language/ru-RU.html
resolve https://github.com/zephir-lang/zephir-website/issues/280
=> remove Discussions link ru

_data/tr-TR.json, language/tr-TR.html
resolve https://github.com/zephir-lang/zephir-website/issues/282
=> remove Discussions link tr

_data/zh-CN.json, language/zh-CN.html
resolve https://github.com/zephir-lang/zephir-website/issues/286
=> remove Discussions link zh

_data/en.json, language/en.html
resolve https://github.com/zephir-lang/zephir-website/issues/288
=> re-name blog to discussions en

_data/el-GR.json, language/el-GR.html
resolve https://github.com/zephir-lang/zephir-website/issues/290
=> re-name blog to discussions el

_data/en-US.json
resolve https://github.com/zephir-lang/zephir-website/issues/292
=> re-name blog to discussions en-us

_data/es-ES.json, language/es-ES.html
resolve https://github.com/zephir-lang/zephir-website/issues/294
=> re-name blog to discussions es

_data/ru-RU.json, language/ru-RU.html
resolve https://github.com/zephir-lang/zephir-website/issues/296
=> re-name blog to discussions ru

_data/tr-TR.json, language/tr-TR.html
resolve https://github.com/zephir-lang/zephir-website/issues/298
=> re-name blog to discussions tr

_data/uk-UA.json, language/uk-UA.html
resolve https://github.com/zephir-lang/zephir-website/issues/300
=> re-name blog to discussions ua

_data/zh-CN.json, language/zh-CN.html
resolve https://github.com/zephir-lang/zephir-website/issues/302
=> re-name blog to discussions zh

language/en.html
resolve https://github.com/zephir-lang/zephir-website/issues/309
=> update footer links

language/el-GR.html
resolve https://github.com/zephir-lang/zephir-website/issues/311
=> update docs links el

language/es-ES.html
resolve https://github.com/zephir-lang/zephir-website/issues/313
=> update docs links es

language/ru-RU.html
resolve https://github.com/zephir-lang/zephir-website/issues/315
=> update docs links ru

language/tr-TR.html
resolve https://github.com/zephir-lang/zephir-website/issues/317
=> update docs links tr

language/uk-UA.html
resolve https://github.com/zephir-lang/zephir-website/issues/319
=> update docs links uk

language/zh-CN.html
resolve https://github.com/zephir-lang/zephir-website/issues/321
=> update docs links zh

language/el-GR.html, language/es-ES.html, language/ru-RU.html, language/tr-TR.html, language/uk-UA.html, language/zh-CN.html
resolve https://github.com/zephir-lang/zephir-website/issues/337
=> add dark theme for other langs

_includes/meta.html
resolve https://github.com/zephir-lang/zephir-website/issues/339
=> add theme preloader
